import { Flow } from '@/types/flow';

export const appointmentsFlow: Flow = {
  id: 'appointments',
  name: 'Manage Appointments',
  description: 'Schedule, cancel, or reschedule appointments',
  icon: 'Calendar',
  steps: [
    {
      id: 'phone',
      question: "Hi! I can help you manage your appointments. What's your phone number?",
      inputType: 'phone',
      required: true,
      placeholder: '(555) 123-4567',
    },
    {
      id: 'for-who',
      question: "Is this appointment for you or someone else?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'me', label: 'Me' },
        { value: 'someone-else', label: 'Someone else' },
      ],
    },
    {
      id: 'patient-name',
      question: "What's the patient's name?",
      inputType: 'text',
      required: true,
      placeholder: 'Full name',
      conditionalOn: { stepId: 'for-who', value: 'someone-else' },
    },
    {
      id: 'action',
      question: "What would you like to do?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'schedule', label: 'Schedule a new appointment' },
        { value: 'cancel', label: 'Cancel an appointment' },
        { value: 'reschedule', label: 'Reschedule an appointment' },
      ],
    },
    // Schedule flow
    {
      id: 'provider-name',
      question: "Who do you want to schedule with?",
      inputType: 'text',
      required: true,
      placeholder: "Doctor or provider's name",
      conditionalOn: { stepId: 'action', value: 'schedule' },
    },
    {
      id: 'provider-contact',
      question: "Do you have their phone number or address? This helps us find the right office.",
      inputType: 'text',
      required: false,
      placeholder: 'Phone number or address (optional)',
      conditionalOn: { stepId: 'action', value: 'schedule' },
    },
    {
      id: 'patient-status',
      question: "Are you a new or existing patient with this provider?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'new', label: 'New patient' },
        { value: 'existing', label: 'Existing patient' },
      ],
      conditionalOn: { stepId: 'action', value: 'schedule' },
    },
    {
      id: 'visit-reason',
      question: "What's the reason for the visit?",
      inputType: 'text',
      required: true,
      placeholder: 'e.g., Annual physical, follow-up, new concern...',
      conditionalOn: { stepId: 'action', value: 'schedule' },
    },
    {
      id: 'schedule-urgency',
      question: "How soon do you want to be seen?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'asap', label: 'ASAP' },
        { value: 'this-week', label: 'This week' },
        { value: 'two-weeks', label: 'Within 2 weeks' },
        { value: 'month', label: 'Within a month' },
        { value: 'flexible', label: 'Flexible' },
      ],
      conditionalOn: { stepId: 'action', value: 'schedule' },
    },
    {
      id: 'preferred-times',
      question: "What days and times work best for you?",
      inputType: 'text',
      required: true,
      placeholder: 'e.g., Weekday mornings, Tuesday afternoons...',
      conditionalOn: { stepId: 'action', value: 'schedule' },
    },
    {
      id: 'fallback-times',
      question: "If those times aren't available, what's your backup preference?",
      inputType: 'text',
      required: false,
      placeholder: 'Alternative days/times...',
      conditionalOn: { stepId: 'action', value: 'schedule' },
    },
    {
      id: 'schedule-booking-preference',
      question: "Do you want us to give you options or just book the best available time?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'options', label: 'Give me options' },
        { value: 'book-it', label: 'Just book it' },
      ],
      conditionalOn: { stepId: 'action', value: 'schedule' },
    },
    {
      id: 'schedule-notes',
      question: "Anything else we should know?",
      inputType: 'text',
      required: false,
      placeholder: 'Special requests, accommodations needed...',
      conditionalOn: { stepId: 'action', value: 'schedule' },
    },
    // Cancel flow
    {
      id: 'cancel-provider-name',
      question: "Which provider is your appointment with?",
      inputType: 'text',
      required: true,
      placeholder: "Doctor or provider's name",
      conditionalOn: { stepId: 'action', value: 'cancel' },
    },
    {
      id: 'cancel-provider-contact',
      question: "Do you have their phone number or address?",
      inputType: 'text',
      required: false,
      placeholder: 'Phone number or address (optional)',
      conditionalOn: { stepId: 'action', value: 'cancel' },
    },
    {
      id: 'cancel-appointment-date',
      question: "When is the appointment you want to cancel?",
      inputType: 'text',
      required: true,
      placeholder: 'Date and time, or approximate',
      conditionalOn: { stepId: 'action', value: 'cancel' },
    },
    {
      id: 'want-to-reschedule',
      question: "Would you like to reschedule this appointment instead?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'yes', label: 'Yes, reschedule it' },
        { value: 'no', label: 'No, just cancel' },
      ],
      conditionalOn: { stepId: 'action', value: 'cancel' },
    },
    {
      id: 'cancel-notes',
      question: "Anything else we should know?",
      inputType: 'text',
      required: false,
      placeholder: 'Any notes...',
      conditionalOn: { stepId: 'action', value: 'cancel' },
      skipIf: { stepId: 'want-to-reschedule', value: 'yes' },
    },
    // Reschedule flow (also triggered from cancel)
    {
      id: 'reschedule-provider-name',
      question: "Which provider is your appointment with?",
      inputType: 'text',
      required: true,
      placeholder: "Doctor or provider's name",
      conditionalOn: { stepId: 'action', value: 'reschedule' },
    },
    {
      id: 'reschedule-provider-contact',
      question: "Do you have their phone number or address?",
      inputType: 'text',
      required: false,
      placeholder: 'Phone number or address (optional)',
      conditionalOn: { stepId: 'action', value: 'reschedule' },
    },
    {
      id: 'current-appointment-date',
      question: "When is your current appointment?",
      inputType: 'text',
      required: true,
      placeholder: "Date and time, or 'I don't remember'",
      conditionalOn: { stepId: 'action', value: 'reschedule' },
    },
    {
      id: 'reschedule-urgency',
      question: "How soon do you want to be seen?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'asap', label: 'ASAP' },
        { value: 'this-week', label: 'This week' },
        { value: 'two-weeks', label: 'Within 2 weeks' },
        { value: 'month', label: 'Within a month' },
        { value: 'flexible', label: 'Flexible' },
      ],
      conditionalOn: { stepId: 'action', value: ['reschedule'] },
    },
    {
      id: 'reschedule-preferred-times',
      question: "What days and times work best for you?",
      inputType: 'text',
      required: true,
      placeholder: 'e.g., Weekday mornings, Tuesday afternoons...',
      conditionalOn: { stepId: 'action', value: ['reschedule'] },
    },
    {
      id: 'reschedule-booking-preference',
      question: "Do you want us to give you options or just book the best available time?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'options', label: 'Give me options' },
        { value: 'book-it', label: 'Just book it' },
      ],
      conditionalOn: { stepId: 'action', value: ['reschedule'] },
    },
    {
      id: 'reschedule-notes',
      question: "Anything else we should know?",
      inputType: 'text',
      required: false,
      placeholder: 'Any notes...',
      conditionalOn: { stepId: 'action', value: ['reschedule'] },
    },
  ],
};
