import { Flow } from '@/types/flow';

export const comparePricesFlow: Flow = {
  id: 'compare-prices',
  name: 'Compare Care Prices',
  description: 'Find savings on prescriptions, procedures, tests, or devices',
  icon: 'DollarSign',
  steps: [
    {
      id: 'price-type',
      question: "What would you like to compare prices for?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'prescription', label: 'Prescription medication', description: 'Find the best price on your meds' },
        { value: 'procedure', label: 'Medical procedure', description: 'Compare surgery or procedure costs' },
        { value: 'test', label: 'Lab or imaging test', description: 'Find affordable testing options' },
        { value: 'device', label: 'Medical device', description: 'Compare DME prices' },
      ],
    },
    // Prescription flow
    {
      id: 'rx-medication',
      question: "What medication do you need? Include the dosage if you know it.",
      inputType: 'text',
      required: true,
      placeholder: 'e.g., Lisinopril 10mg',
      conditionalOn: { stepId: 'price-type', value: 'prescription' },
    },
    {
      id: 'rx-quantity',
      question: "What quantity or days supply do you need?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: '30', label: '30 days' },
        { value: '90', label: '90 days' },
        { value: 'other', label: 'Other' },
      ],
      conditionalOn: { stepId: 'price-type', value: 'prescription' },
    },
    {
      id: 'rx-generic-ok',
      question: "Is generic acceptable?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'yes', label: 'Yes, generic is fine' },
        { value: 'brand-only', label: 'Brand name only' },
      ],
      conditionalOn: { stepId: 'price-type', value: 'prescription' },
    },
    {
      id: 'rx-has-prescription',
      question: "Do you have a current prescription for this?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No' },
        { value: 'expired', label: 'Expired' },
      ],
      conditionalOn: { stepId: 'price-type', value: 'prescription' },
    },
    {
      id: 'rx-current-payment',
      question: "How do you currently pay for this medication?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'cash', label: 'Cash' },
        { value: 'insurance', label: 'Insurance' },
        { value: 'discount-card', label: 'Discount card (GoodRx, etc.)' },
        { value: 'not-filling', label: "I don't fill this yet" },
      ],
      conditionalOn: { stepId: 'price-type', value: 'prescription' },
    },
    {
      id: 'rx-current-price',
      question: "How much do you currently pay (if known)?",
      inputType: 'number',
      required: false,
      placeholder: 'Current price in dollars',
      conditionalOn: { stepId: 'price-type', value: 'prescription' },
    },
    {
      id: 'rx-mail-order',
      question: "Are you open to mail-order pharmacies?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No, local pickup only' },
      ],
      conditionalOn: { stepId: 'price-type', value: 'prescription' },
    },
    {
      id: 'rx-zipcode',
      question: "What's your zip code?",
      inputType: 'zipcode',
      required: true,
      placeholder: 'Zip code',
      conditionalOn: { stepId: 'price-type', value: 'prescription' },
    },
    {
      id: 'rx-notes',
      question: "Anything else we should know?",
      inputType: 'text',
      required: false,
      placeholder: 'Additional notes...',
      conditionalOn: { stepId: 'price-type', value: 'prescription' },
    },
    // Procedure flow
    {
      id: 'procedure-name',
      question: "What procedure do you need?",
      inputType: 'text',
      required: true,
      placeholder: 'e.g., MRI of knee, colonoscopy...',
      conditionalOn: { stepId: 'price-type', value: 'procedure' },
    },
    {
      id: 'procedure-code',
      question: "Do you have a CPT code? (optional)",
      inputType: 'text',
      required: false,
      placeholder: 'CPT code if known',
      conditionalOn: { stepId: 'price-type', value: 'procedure' },
    },
    {
      id: 'procedure-recommended',
      question: "Has a doctor recommended this procedure?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: "No, I'm researching" },
      ],
      conditionalOn: { stepId: 'price-type', value: 'procedure' },
    },
    {
      id: 'procedure-payment',
      question: "How do you want to pay?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'insurance', label: 'Use my insurance' },
        { value: 'cash', label: 'Cash price' },
        { value: 'both', label: 'Compare both' },
      ],
      conditionalOn: { stepId: 'price-type', value: 'procedure' },
    },
    {
      id: 'procedure-insurance-card',
      question: "Please upload your insurance card.",
      inputType: 'photo-upload',
      required: true,
      conditionalOn: { stepId: 'procedure-payment', value: ['insurance', 'both'] },
    },
    {
      id: 'procedure-zipcode',
      question: "What's your zip code?",
      inputType: 'zipcode',
      required: true,
      placeholder: 'Zip code',
      conditionalOn: { stepId: 'price-type', value: 'procedure' },
    },
    {
      id: 'procedure-travel',
      question: "How far are you willing to travel?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: '15', label: '15 minutes' },
        { value: '30', label: '30 minutes' },
        { value: '45', label: '45 minutes' },
        { value: '60+', label: '60+ minutes' },
      ],
      conditionalOn: { stepId: 'price-type', value: 'procedure' },
    },
    {
      id: 'procedure-timing',
      question: "When do you need this done?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'asap', label: 'ASAP' },
        { value: '1-month', label: 'Within 1 month' },
        { value: '3-months', label: 'Within 3 months' },
        { value: 'flexible', label: 'Flexible' },
      ],
      conditionalOn: { stepId: 'price-type', value: 'procedure' },
    },
    {
      id: 'procedure-notes',
      question: "Anything else we should know?",
      inputType: 'text',
      required: false,
      placeholder: 'Additional notes...',
      conditionalOn: { stepId: 'price-type', value: 'procedure' },
    },
    // Test flow
    {
      id: 'test-name',
      question: "What test do you need?",
      inputType: 'text',
      required: true,
      placeholder: 'e.g., Complete blood count, chest X-ray...',
      conditionalOn: { stepId: 'price-type', value: 'test' },
    },
    {
      id: 'test-order',
      question: "Do you have a doctor's order for this test?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No' },
        { value: 'can-get', label: 'I can get one' },
      ],
      conditionalOn: { stepId: 'price-type', value: 'test' },
    },
    {
      id: 'test-results-destination',
      question: "Do you need results sent to a specific provider?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No, just to me' },
      ],
      conditionalOn: { stepId: 'price-type', value: 'test' },
    },
    {
      id: 'test-provider-info',
      question: "Where should we send the results? (Provider name and fax)",
      inputType: 'text',
      required: true,
      placeholder: "Provider name and fax number",
      conditionalOn: { stepId: 'test-results-destination', value: 'yes' },
    },
    {
      id: 'test-zipcode',
      question: "What's your zip code?",
      inputType: 'zipcode',
      required: true,
      placeholder: 'Zip code',
      conditionalOn: { stepId: 'price-type', value: 'test' },
    },
    {
      id: 'test-travel',
      question: "How far are you willing to travel?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: '15', label: '15 minutes' },
        { value: '30', label: '30 minutes' },
        { value: '45', label: '45 minutes' },
        { value: '60+', label: '60+ minutes' },
      ],
      conditionalOn: { stepId: 'price-type', value: 'test' },
    },
    {
      id: 'test-notes',
      question: "Anything else we should know?",
      inputType: 'text',
      required: false,
      placeholder: 'Additional notes...',
      conditionalOn: { stepId: 'price-type', value: 'test' },
    },
    // Device flow
    {
      id: 'device-name',
      question: "What medical device do you need?",
      inputType: 'text',
      required: true,
      placeholder: 'e.g., CPAP machine, wheelchair, blood pressure monitor...',
      conditionalOn: { stepId: 'price-type', value: 'device' },
    },
    {
      id: 'device-duration',
      question: "Is this a temporary or permanent need?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'temporary', label: 'Temporary' },
        { value: 'permanent', label: 'Permanent' },
        { value: 'not-sure', label: 'Not sure' },
      ],
      conditionalOn: { stepId: 'price-type', value: 'device' },
    },
    {
      id: 'device-rent-buy',
      question: "Would you prefer to rent or buy?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'rent', label: 'Rent' },
        { value: 'buy', label: 'Buy' },
        { value: 'cheapest', label: 'Whichever is cheaper' },
      ],
      conditionalOn: { stepId: 'price-type', value: 'device' },
    },
    {
      id: 'device-prescription',
      question: "Do you have a prescription for this device?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No' },
        { value: 'not-sure', label: 'Not sure if needed' },
      ],
      conditionalOn: { stepId: 'price-type', value: 'device' },
    },
    {
      id: 'device-refurbished',
      question: "Is refurbished or used acceptable?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'new-only', label: 'New only' },
      ],
      conditionalOn: { stepId: 'price-type', value: 'device' },
    },
    {
      id: 'device-delivery',
      question: "Do you need delivery?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'yes', label: 'Yes, deliver to me' },
        { value: 'no', label: "No, I'll pick up" },
      ],
      conditionalOn: { stepId: 'price-type', value: 'device' },
    },
    {
      id: 'device-address',
      question: "What's the delivery address?",
      inputType: 'address',
      required: true,
      placeholder: 'Full delivery address',
      conditionalOn: { stepId: 'device-delivery', value: 'yes' },
    },
    {
      id: 'device-zipcode',
      question: "What's your zip code?",
      inputType: 'zipcode',
      required: true,
      placeholder: 'Zip code',
      conditionalOn: { stepId: 'device-delivery', value: 'no' },
    },
    {
      id: 'device-notes',
      question: "Anything else we should know?",
      inputType: 'text',
      required: false,
      placeholder: 'Additional notes...',
      conditionalOn: { stepId: 'price-type', value: 'device' },
    },
  ],
};
