import { Flow } from '@/types/flow';

export const findCareFlow: Flow = {
  id: 'find-care',
  name: 'Find Care',
  description: 'Find a healthcare provider that matches your needs',
  icon: 'Search',
  steps: [
    {
      id: 'for-who',
      question: "Hi! I'll help you find the right care. First, is this for you or someone else?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'me', label: 'Me' },
        { value: 'someone-else', label: 'Someone else' },
      ],
    },
    {
      id: 'patient-name',
      question: "What's the patient's name?",
      inputType: 'text',
      required: true,
      placeholder: 'Full name',
      conditionalOn: { stepId: 'for-who', value: 'someone-else' },
    },
    {
      id: 'patient-relationship',
      question: "What's your relationship to this person?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'child', label: 'Child' },
        { value: 'spouse', label: 'Spouse/Partner' },
        { value: 'parent', label: 'Parent' },
        { value: 'other', label: 'Other' },
      ],
      conditionalOn: { stepId: 'for-who', value: 'someone-else' },
    },
    {
      id: 'phone',
      question: "What's your phone number? We'll use this to follow up with you.",
      inputType: 'phone',
      required: true,
      placeholder: '(555) 123-4567',
    },
    {
      id: 'care-type',
      question: "What kind of care are you looking for? You can describe symptoms or name a specialty.",
      inputType: 'text',
      required: true,
      placeholder: 'e.g., dermatologist, back pain, annual physical...',
    },
    {
      id: 'location',
      question: "Where do you need care? Enter a zip code or share your location.",
      inputType: 'location',
      required: true,
      placeholder: 'Zip code',
    },
    {
      id: 'travel-distance',
      question: "How far are you willing to travel?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: '15', label: '15 minutes' },
        { value: '30', label: '30 minutes' },
        { value: '45', label: '45 minutes' },
        { value: '60+', label: '60+ minutes' },
      ],
    },
    {
      id: 'dob',
      question: "What's the patient's date of birth?",
      inputType: 'date',
      required: true,
    },
    {
      id: 'urgency',
      question: "How soon do you need to be seen?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'asap', label: 'ASAP / Urgent' },
        { value: 'this-week', label: 'This week' },
        { value: 'two-weeks', label: 'Within 2 weeks' },
        { value: 'flexible', label: 'Flexible' },
      ],
    },
    {
      id: 'insurance-needed',
      question: "Does this need to be covered by insurance?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: "No, I'll pay cash" },
        { value: 'not-sure', label: 'Not sure' },
      ],
    },
    {
      id: 'insurance-card',
      question: "Please upload a photo of your insurance card (front and back).",
      inputType: 'photo-upload',
      required: true,
      conditionalOn: { stepId: 'insurance-needed', value: ['yes', 'not-sure'] },
    },
    {
      id: 'visit-type',
      question: "Do you prefer in-person or telehealth?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'in-person-only', label: 'In-person only' },
        { value: 'in-person-preferred', label: 'In-person preferred' },
        { value: 'telehealth-preferred', label: 'Telehealth preferred' },
        { value: 'telehealth-only', label: 'Telehealth only' },
        { value: 'no-preference', label: 'No preference' },
      ],
    },
    {
      id: 'gender-preference',
      question: "Do you have a gender preference for your provider?",
      inputType: 'single-select',
      required: false,
      options: [
        { value: 'no-preference', label: 'No preference' },
        { value: 'male', label: 'Male' },
        { value: 'female', label: 'Female' },
        { value: 'non-binary', label: 'Non-binary' },
      ],
    },
    {
      id: 'language',
      question: "Do you need a provider who speaks a specific language (other than English)?",
      inputType: 'text',
      required: false,
      placeholder: 'e.g., Spanish, Mandarin, or skip',
    },
    {
      id: 'problem-details',
      question: "Tell us more about the problem you're having. The more detail, the better we can help.",
      inputType: 'text',
      required: false,
      placeholder: 'Describe your symptoms, concerns, or what you need help with...',
    },
    {
      id: 'booking-preference',
      question: "Would you like us to give you options to choose from, or just book the best match for you?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'options', label: 'Give me options' },
        { value: 'book-it', label: 'Just book it for me' },
      ],
    },
    {
      id: 'other-notes',
      question: "Anything else we should know?",
      inputType: 'text',
      required: false,
      placeholder: 'Additional preferences or notes...',
    },
  ],
};
