import { Flow } from '@/types/flow';

export const medicalRecordsFlow: Flow = {
  id: 'medical-records',
  name: 'Medical Records',
  description: 'Get or transfer your medical records',
  icon: 'FileText',
  steps: [
    {
      id: 'phone',
      question: "Hi! I can help you get or transfer your medical records. What's your phone number?",
      inputType: 'phone',
      required: true,
      placeholder: '(555) 123-4567',
    },
    {
      id: 'full-name',
      question: "What's your full legal name as it appears in your medical records?",
      inputType: 'text',
      required: true,
      placeholder: 'Full legal name',
    },
    {
      id: 'dob',
      question: "What's your date of birth?",
      inputType: 'date',
      required: true,
    },
    {
      id: 'for-who',
      question: "Are you requesting records for yourself or someone else?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'me', label: 'Myself' },
        { value: 'someone-else', label: 'Someone else' },
      ],
    },
    {
      id: 'has-authorization',
      question: "Do you have signed authorization from the patient?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No' },
      ],
      conditionalOn: { stepId: 'for-who', value: 'someone-else' },
    },
    {
      id: 'authorization-upload',
      question: "Please upload the signed authorization form.",
      inputType: 'file-upload',
      required: true,
      conditionalOn: { stepId: 'has-authorization', value: 'yes' },
    },
    {
      id: 'records-location',
      question: "Where are your records currently? (Provider or facility name)",
      inputType: 'text',
      required: true,
      placeholder: "Doctor's name, hospital, clinic...",
    },
    {
      id: 'records-location-contact',
      question: "Do you have their phone number or address?",
      inputType: 'text',
      required: false,
      placeholder: 'Phone number or address (optional)',
    },
    {
      id: 'date-range',
      question: "What date range of records do you need?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'all', label: 'All records' },
        { value: 'last-year', label: 'Last year' },
        { value: 'last-5-years', label: 'Last 5 years' },
        { value: 'specific', label: 'Specific dates' },
      ],
    },
    {
      id: 'specific-dates',
      question: "What date range? (Start and end dates)",
      inputType: 'text',
      required: true,
      placeholder: 'e.g., January 2023 - June 2024',
      conditionalOn: { stepId: 'date-range', value: 'specific' },
    },
    {
      id: 'record-types',
      question: "What type of records do you need?",
      inputType: 'multi-select',
      required: true,
      options: [
        { value: 'complete', label: 'Complete file' },
        { value: 'visit-notes', label: 'Visit notes' },
        { value: 'labs', label: 'Lab results' },
        { value: 'imaging', label: 'Imaging (X-rays, MRIs, etc.)' },
        { value: 'immunizations', label: 'Immunizations' },
        { value: 'other', label: 'Other' },
      ],
    },
    {
      id: 'destination',
      question: "Where do you want the records sent?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'provider', label: 'To another provider' },
        { value: 'me-email', label: 'To me (email)' },
        { value: 'me-mail', label: 'To me (physical mail)' },
        { value: 'store', label: 'Just store them for me in the app' },
      ],
    },
    {
      id: 'destination-provider',
      question: "Where should we send them? (Provider name, address, and fax)",
      inputType: 'text',
      required: true,
      placeholder: 'Provider name, address, fax number',
      conditionalOn: { stepId: 'destination', value: 'provider' },
    },
    {
      id: 'destination-email',
      question: "What's your email address?",
      inputType: 'email',
      required: true,
      placeholder: 'your@email.com',
      conditionalOn: { stepId: 'destination', value: 'me-email' },
    },
    {
      id: 'destination-mail',
      question: "What's your mailing address?",
      inputType: 'address',
      required: true,
      placeholder: 'Full mailing address',
      conditionalOn: { stepId: 'destination', value: 'me-mail' },
    },
    {
      id: 'certified-copies',
      question: "Do you need certified copies?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No' },
        { value: 'not-sure', label: 'Not sure' },
      ],
    },
    {
      id: 'store-copy',
      question: "Would you like us to keep a copy on file for your future use?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No' },
      ],
      skipIf: { stepId: 'destination', value: 'store' },
    },
    {
      id: 'fees-acknowledged',
      question: "Note: Some providers charge fees for records (typically $10-50). We'll let you know if any fees apply. Is that okay?",
      inputType: 'single-select',
      required: true,
      options: [
        { value: 'yes', label: 'Yes, I understand' },
        { value: 'no', label: "No, only if it's free" },
      ],
    },
    {
      id: 'other-notes',
      question: "Anything else we should know?",
      inputType: 'text',
      required: false,
      placeholder: 'Additional notes...',
    },
  ],
};
